development:
  adapter: sqlite3
  encoding: unicode
  database: db/accompany_me_development.sqlite3
  pool: 5

test:
  adapter: sqlite3
  encoding: unicode
  database: db/accompany_me_test.sqlite3
  pool: 5

production:
  adapter: postgresql
  encoding: unicode
  database: accompany_me_production
  pool: 5
